name = "bootstrap-dev"
type = "webpack"
account_id = "18ff2b4e6205b938652998cfca0d8cff"
workers_dev = true
webpack_config = "webpack.config.js"
kv_namespaces = [
 { binding = "BOOTSTRAP", id = "95561bdb2dbc41e8bf6e2975e49a1f6c", preview_id = "30ff63d04cb5433db469a041f67783da" }
]
vars = { ENVIRONMENT = "dev" }

[env.production]
name = "bootstrap"
workers_dev = false
vars = { ENVIRONMENT = "production" }
route = "bootstrap.holo.host"
zone_id = "35f34e8f9d04ef8c87283ea9fb812989"
kv_namespaces = [
 { binding = "BOOTSTRAP", id = "95561bdb2dbc41e8bf6e2975e49a1f6c" }
]

[env.staging]
name = "bootstrap-staging"
workers_dev = false
vars = { ENVIRONMENT = "production" }
route = "bootstrap-staging.holo.host"
zone_id = "35f34e8f9d04ef8c87283ea9fb812989"
kv_namespaces = [
 { binding = "BOOTSTRAP", id = "70f408b5d16b4822b93f2513e6344aef" }
]
